# Generated by Django 4.1.4 on 2023-03-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mock_exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitMock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                ("answers", models.JSONField(default=dict)),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mock_exam.mockexam")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "모의고사 제출 답",
                "verbose_name_plural": "모의고사 제출 답",
                "db_table": "submit_mock",
                "ordering": ["-created_at"],
            },
        ),
    ]
