# Generated by Django 4.1.4 on 2023-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioncategory",
            name="name",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "스택&큐"), (2, "완전탐색"), (3, "DP"), (4, "BFS")], max_length=32, verbose_name="유형 이름"
            ),
        ),
    ]
