# Generated by Django 4.1.4 on 2023-03-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_alter_questioncategory_name"),
        ("explanation", "0002_alter_explanation_options_explanation_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="explanation",
            name="answer",
        ),
        migrations.AddField(
            model_name="explanation",
            name="question",
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to="question.question"),
            preserve_default=False,
        ),
    ]
