# Generated by Django 4.1.4 on 2023-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit_answer", "0003_submitanswer_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitanswer",
            name="status",
            field=models.PositiveSmallIntegerField(choices=[(1, "채점 중"), (2, "채점 완료")], default=1, verbose_name="상태"),
            preserve_default=False,
        ),
    ]
