# Generated by Django 4.1.4 on 2023-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit_answer", "0005_alter_submitanswer_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitanswer",
            name="score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="점수"),
        ),
    ]
