# Generated by Django 4.1.4 on 2023-03-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_alter_questioncategory_name"),
        ("answer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="question.question"),
        ),
    ]
