# Generated by Django 4.1.4 on 2023-03-12 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('title', models.CharField(max_length=64, verbose_name='시험지 명')),
                ('text', models.TextField(verbose_name='내용')),
                ('time_limit', models.SmallIntegerField(verbose_name='제한 시간')),
            ],
            options={
                'verbose_name': '모의고사',
                'verbose_name_plural': '모의고사',
                'db_table': 'test_paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionInTestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_paper.testpaper')),
            ],
            options={
                'verbose_name': '모의고사 문제',
                'verbose_name_plural': '모의고사 문제',
                'db_table': 'question_test_paper',
                'ordering': ['-created_at'],
            },
        ),
    ]
